use std::path::{Path, PathBuf};

use wax_core::{Cell, CellType, CellValue};
use wax_fmt::{render, FmtValue};
use wax_read::{CalamineReader, Reader, ReaderOptions};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn cell(cells: &[Cell], row: u32, col: u32) -> &Cell {
    cells
        .iter()
        .find(|cell| (cell.r, cell.c) == (row, col))
        .expect("fixture cell should be present")
}

// reader.xlsx is a hand-authored minimal OOXML package generated by the
// adjacent generate-reader-fixture.sh script. It intentionally combines
// shared strings, formulas, 1904 dates, merges, and style-table references.
#[test]
fn normalizes_xlsx_values_dates_formulas_merges_and_formats() {
    let document = CalamineReader.read(&fixture("reader.xlsx"), ReaderOptions::default());

    assert!(document.ok, "{:?}", document.error);
    assert!(document.warnings.is_empty());
    assert_eq!(document.sheets.len(), 1);
    let sheet = &document.sheets[0];
    assert_eq!(sheet.name, "Reader");
    assert_eq!((sheet.rows, sheet.cols), (4, 7));
    assert_eq!(sheet.merges, ["A3:B3", "D3:F4"]);
    assert_eq!(sheet.cells.len(), 15);

    assert_eq!(
        cell(&sheet.cells, 0, 0).v,
        Some(CellValue::Text("Hello shared".to_owned()))
    );
    assert_eq!(
        cell(&sheet.cells, 0, 5).v,
        Some(CellValue::Text("Rich text".to_owned()))
    );
    assert_eq!(cell(&sheet.cells, 0, 1).t, CellType::B);
    assert_eq!(cell(&sheet.cells, 0, 1).v, Some(CellValue::Bool(true)));
    assert_eq!(cell(&sheet.cells, 0, 2).t, CellType::E);
    assert_eq!(
        cell(&sheet.cells, 0, 2).v,
        Some(CellValue::Text("#DIV/0!".to_owned()))
    );

    let custom_date = cell(&sheet.cells, 0, 3);
    assert_eq!(custom_date.t, CellType::D);
    assert_eq!(
        custom_date.v,
        Some(CellValue::Text("1904-01-01".to_owned()))
    );
    assert_eq!(custom_date.fmt.as_deref(), Some("yyyy-mm-dd"));
    let builtin_date = cell(&sheet.cells, 0, 4);
    assert_eq!(
        builtin_date.v,
        Some(CellValue::Text("1904-01-02".to_owned()))
    );
    assert_eq!(builtin_date.fmt.as_deref(), Some("mm-dd-yy"));
    assert_eq!(cell(&sheet.cells, 0, 6).fmt.as_deref(), Some("#,##0.00"));
    assert_eq!(
        cell(&sheet.cells, 1, 6).fmt.as_deref(),
        Some("0.0000 \"widgets\"")
    );

    let numeric_formula = cell(&sheet.cells, 1, 2);
    assert_eq!(numeric_formula.f.as_deref(), Some("SUM(A2:B2)"));
    assert_eq!(numeric_formula.v, Some(CellValue::Number(5.0)));
    let string_formula = cell(&sheet.cells, 1, 3);
    assert_eq!(string_formula.f.as_deref(), Some("CONCAT(\"x\",\"y\")"));
    assert_eq!(string_formula.v, Some(CellValue::Text("xy".to_owned())));

    let declared_uncached = cell(&sheet.cells, 1, 4);
    assert_eq!(declared_uncached.t, CellType::N);
    assert_eq!(declared_uncached.v, None);
    assert_eq!(declared_uncached.f.as_deref(), Some("A2/0"));
    let undeclared_uncached = cell(&sheet.cells, 1, 5);
    assert_eq!(undeclared_uncached.t, CellType::S);
    assert_eq!(undeclared_uncached.v, None);
    assert_eq!(undeclared_uncached.f.as_deref(), Some("UNSUPPORTED()"));
}

#[test]
fn display_strings_are_delegated_to_wax_fmt_with_raw_values() {
    let document = CalamineReader.read(&fixture("reader.xlsx"), ReaderOptions::default());
    let cells = &document.sheets[0].cells;

    assert_eq!(
        cell(cells, 0, 0).d,
        render("General", FmtValue::Text("Hello shared"), true)
    );
    assert_eq!(
        cell(cells, 0, 1).d,
        render("General", FmtValue::Bool(true), true)
    );
    assert_eq!(
        cell(cells, 0, 2).d,
        render("General", FmtValue::Error("#DIV/0!"), true)
    );
    assert_eq!(
        cell(cells, 0, 3).d,
        render("yyyy-mm-dd", FmtValue::Number(0.0), true)
    );
    assert_eq!(
        cell(cells, 0, 4).d,
        render("mm-dd-yy", FmtValue::Number(1.0), true)
    );
    assert_eq!(
        cell(cells, 1, 2).d,
        render("General", FmtValue::Number(5.0), true)
    );
    assert_eq!(
        cell(cells, 1, 6).d,
        render("0.0000 \"widgets\"", FmtValue::Number(12.3456), true)
    );
}

#[test]
fn global_cell_cap_is_loud_and_preserves_extent() {
    let document = CalamineReader.read(
        &fixture("reader.xlsx"),
        ReaderOptions {
            max_cells: 4,
            ..ReaderOptions::default()
        },
    );

    assert!(document.ok);
    assert!(document.truncated);
    assert_eq!(document.sheets[0].cells.len(), 4);
    assert!(document.sheets[0].truncated);
    assert_eq!((document.sheets[0].rows, document.sheets[0].cols), (4, 7));
    assert_eq!(document.sheets[0].merges, ["A3:B3", "D3:F4"]);
}

#[test]
fn corrupt_zip_is_a_normalized_failure() {
    let document = CalamineReader.read(&fixture("corrupt.xlsx"), ReaderOptions::default());

    assert!(!document.ok);
    assert_eq!(
        document.error.expect("error should be populated").code,
        "bad_zip"
    );
}

#[test]
fn zero_timeout_is_reported_before_parsing() {
    let document = CalamineReader.read(
        &fixture("reader.xlsx"),
        ReaderOptions {
            timeout_ms: 0,
            ..ReaderOptions::default()
        },
    );

    assert!(!document.ok);
    assert_eq!(
        document.error.expect("error should be populated").code,
        "timeout"
    );
}

// These three binary smoke fixtures are copied unchanged from calamine
// v0.36.1 (git 0a24c2a9f1e38c0932c1299e633270dc730db505), MIT licensed:
// tests/date.xls, tests/issues.ods, and tests/date_1904.xlsb.
#[test]
fn legacy_xls_ods_and_xlsb_open_without_panicking() {
    for name in ["date.xls", "issues.ods", "date_1904.xlsb"] {
        let document = CalamineReader.read(&fixture(name), ReaderOptions::default());
        assert!(document.ok, "{name}: {:?}", document.error);
        assert!(!document.sheets.is_empty(), "{name}");
        assert!(
            document.sheets.iter().any(|sheet| !sheet.cells.is_empty()),
            "{name}"
        );
    }
}
