use std::fs::File;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};

use tempfile::NamedTempFile;
use wax_core::{Cell, CellStyle, CellType, CellValue, ColInfo};
use wax_fmt::{render, FmtValue};
use wax_read::{read_with_deadline, CalamineReader, Reader, ReaderOptions};
use zip::write::SimpleFileOptions;
use zip::{ZipArchive, ZipWriter};

fn fixture(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join(name)
}

fn cell(cells: &[Cell], row: u32, col: u32) -> &Cell {
    cells
        .iter()
        .find(|cell| (cell.r, cell.c) == (row, col))
        .expect("fixture cell should be present")
}

fn fixture_with_replaced_part(part: &str, replacement: &[u8]) -> NamedTempFile {
    let source = File::open(fixture("reader.xlsx")).expect("reader fixture should open");
    let mut source = ZipArchive::new(source).expect("reader fixture should be a zip");
    let output = tempfile::Builder::new()
        .suffix(".xlsx")
        .tempfile()
        .expect("temporary fixture should be created");
    let mut archive = ZipWriter::new(output.reopen().expect("temporary fixture should reopen"));
    for index in 0..source.len() {
        let mut entry = source.by_index(index).expect("fixture entry should open");
        if entry.is_dir() {
            continue;
        }
        let mut bytes = Vec::new();
        entry
            .read_to_end(&mut bytes)
            .expect("fixture entry should read");
        archive
            .start_file(entry.name(), SimpleFileOptions::default())
            .expect("temporary fixture entry should start");
        archive
            .write_all(if entry.name() == part {
                replacement
            } else {
                &bytes
            })
            .expect("temporary fixture entry should write");
    }
    archive.finish().expect("temporary fixture should finish");
    output
}

// reader.xlsx is a hand-authored minimal OOXML package generated by the
// adjacent generate-reader-fixture.sh script. It intentionally combines
// shared strings, formulas, 1904 dates, merges, column widths, and style-table
// references.
#[test]
fn normalizes_xlsx_values_dates_formulas_merges_and_formats() {
    let document = CalamineReader.read(&fixture("reader.xlsx"), ReaderOptions::default());

    assert!(document.ok, "{:?}", document.error);
    assert!(document.warnings.is_empty());
    assert_eq!(document.sheets.len(), 1);
    let sheet = &document.sheets[0];
    assert_eq!(sheet.name, "Reader");
    assert_eq!((sheet.rows, sheet.cols), (4, 7));
    assert_eq!(sheet.merges, ["A3:B3", "D3:F4"]);
    assert_eq!(sheet.cells.len(), 15);
    assert_eq!(
        sheet.col_infos,
        [
            ColInfo { c: 0, width: 12.5 },
            ColInfo { c: 1, width: 20.0 },
            ColInfo { c: 2, width: 20.0 },
            ColInfo { c: 3, width: 20.0 },
            ColInfo { c: 6, width: 15.25 },
        ]
    );
    assert_eq!(
        document.styles,
        [
            CellStyle {
                bold: true,
                italic: true,
                underline: true,
                strike: true,
                font_size: Some(13.5),
                font_name: Some("Aptos Display".to_owned()),
                font_color: Some("#1A2B3C".to_owned()),
                fill_color: Some("#EEDDCC".to_owned()),
            },
            CellStyle {
                font_color: Some("#969696".to_owned()),
                fill_color: Some("#9999FF".to_owned()),
                ..CellStyle::default()
            },
        ]
    );

    assert_eq!(
        cell(&sheet.cells, 0, 0).v,
        Some(CellValue::Text("Hello shared".to_owned()))
    );
    assert_eq!(
        cell(&sheet.cells, 0, 5).v,
        Some(CellValue::Text("Rich text".to_owned()))
    );
    assert_eq!(cell(&sheet.cells, 0, 1).t, CellType::B);
    assert_eq!(cell(&sheet.cells, 0, 1).v, Some(CellValue::Bool(true)));
    assert_eq!(cell(&sheet.cells, 0, 2).t, CellType::E);
    assert_eq!(
        cell(&sheet.cells, 0, 2).v,
        Some(CellValue::Text("#DIV/0!".to_owned()))
    );

    let custom_date = cell(&sheet.cells, 0, 3);
    assert_eq!(custom_date.t, CellType::D);
    assert_eq!(
        custom_date.v,
        Some(CellValue::Text("1904-01-01".to_owned()))
    );
    assert_eq!(custom_date.fmt.as_deref(), Some("yyyy-mm-dd"));
    assert_eq!(custom_date.s, Some(0));
    let builtin_date = cell(&sheet.cells, 0, 4);
    assert_eq!(
        builtin_date.v,
        Some(CellValue::Text("1904-01-02".to_owned()))
    );
    assert_eq!(builtin_date.fmt.as_deref(), Some("mm-dd-yy"));
    assert_eq!(builtin_date.s, Some(0), "duplicate styles share one id");
    assert_eq!(cell(&sheet.cells, 0, 6).fmt.as_deref(), Some("#,##0.00"));
    assert_eq!(cell(&sheet.cells, 0, 6).s, Some(1));
    assert_eq!(
        cell(&sheet.cells, 1, 6).fmt.as_deref(),
        Some("0.0000 \"widgets\"")
    );
    assert_eq!(
        cell(&sheet.cells, 1, 6).s,
        None,
        "theme-only style becomes fully default"
    );

    let numeric_formula = cell(&sheet.cells, 1, 2);
    assert_eq!(numeric_formula.f.as_deref(), Some("SUM(A2:B2)"));
    assert_eq!(numeric_formula.v, Some(CellValue::Number(5.0)));
    let string_formula = cell(&sheet.cells, 1, 3);
    assert_eq!(string_formula.f.as_deref(), Some("CONCAT(\"x\",\"y\")"));
    assert_eq!(string_formula.v, Some(CellValue::Text("xy".to_owned())));

    let declared_uncached = cell(&sheet.cells, 1, 4);
    assert_eq!(declared_uncached.t, CellType::N);
    assert_eq!(declared_uncached.v, None);
    assert_eq!(declared_uncached.f.as_deref(), Some("A2/0"));
    let undeclared_uncached = cell(&sheet.cells, 1, 5);
    assert_eq!(undeclared_uncached.t, CellType::S);
    assert_eq!(undeclared_uncached.v, None);
    assert_eq!(undeclared_uncached.f.as_deref(), Some("UNSUPPORTED()"));
}

#[test]
fn unstyled_xlsx_dump_stays_byte_identical_to_the_pre_w4_shape() {
    let mut document = CalamineReader.read(&fixture("unstyled.xlsx"), ReaderOptions::default());
    assert!(document.ok, "{:?}", document.error);
    document.file = "unstyled.xlsx".to_owned();

    let json = serde_json::to_string(&document).expect("document should serialize");
    assert_eq!(
        json,
        concat!(
            r#"{"schema":1,"tool":"wax","toolVersion":"0.1.0","file":"unstyled.xlsx","#,
            r#""sha256":"","ok":true,"error":null,"wallMs":0,"peakRssBytes":null,"#,
            r#""truncated":false,"sheets":[{"name":"Plain","index":0,"rows":2,"cols":2,"#,
            r#""truncated":false,"merges":[],"cells":[{"r":0,"c":0,"t":"n","v":42.5,"#,
            r#""d":"42.5","f":null,"fmt":null},{"r":0,"c":1,"t":"s","v":"Plain","#,
            r#""d":"Plain","f":null,"fmt":null},{"r":1,"c":0,"t":"b","v":true,"#,
            r#""d":"TRUE","f":null,"fmt":null}]}],"warnings":[]}"#,
        )
    );
}

#[test]
fn malformed_style_attributes_keep_formats_and_valid_neighbor_styles() {
    let malformed = include_str!("fixtures/reader-src/xl/styles.xml")
        .replace(r#"rgb="FF1A2B3C""#, r#"rgb="not-a-color""#);
    let fixture = fixture_with_replaced_part("xl/styles.xml", malformed.as_bytes());
    let document = read_with_deadline(CalamineReader, fixture.path(), ReaderOptions::default());

    assert!(document.ok, "{:?}", document.error);
    assert!(!document
        .warnings
        .iter()
        .any(|warning| warning.contains("xlsx styles could not be read")));

    let cells = &document.sheets[0].cells;
    assert_eq!(cell(cells, 0, 3).fmt.as_deref(), Some("yyyy-mm-dd"));
    assert_eq!(cell(cells, 0, 4).fmt.as_deref(), Some("mm-dd-yy"));
    assert_eq!(cell(cells, 0, 3).s, Some(0));
    assert_eq!(cell(cells, 0, 4).s, Some(0));
    assert_eq!(cell(cells, 0, 6).s, Some(1));
    assert_eq!(
        document.styles,
        [
            CellStyle {
                fill_color: Some("#EEDDCC".to_owned()),
                ..CellStyle::default()
            },
            CellStyle {
                font_color: Some("#969696".to_owned()),
                fill_color: Some("#9999FF".to_owned()),
                ..CellStyle::default()
            }
        ]
    );
}

#[test]
fn malformed_column_declarations_degrade_without_losing_styles() {
    let malformed = include_str!("fixtures/reader-src/xl/worksheets/sheet1.xml")
        .replace(r#"customWidth="true""#, r#"customWidth="maybe""#);
    let fixture = fixture_with_replaced_part("xl/worksheets/sheet1.xml", malformed.as_bytes());
    let document = read_with_deadline(CalamineReader, fixture.path(), ReaderOptions::default());

    assert!(document.ok, "{:?}", document.error);
    assert!(document
        .warnings
        .iter()
        .any(|warning| warning.contains("xlsx column widths")));
    assert!(document.sheets[0].col_infos.is_empty());
    assert!(!document.styles.is_empty());
}

#[test]
fn display_strings_are_delegated_to_wax_fmt_with_raw_values() {
    let document = CalamineReader.read(&fixture("reader.xlsx"), ReaderOptions::default());
    let cells = &document.sheets[0].cells;

    assert_eq!(
        cell(cells, 0, 0).d,
        render("General", FmtValue::Text("Hello shared"), true)
    );
    assert_eq!(
        cell(cells, 0, 1).d,
        render("General", FmtValue::Bool(true), true)
    );
    assert_eq!(
        cell(cells, 0, 2).d,
        render("General", FmtValue::Error("#DIV/0!"), true)
    );
    assert_eq!(
        cell(cells, 0, 3).d,
        render("yyyy-mm-dd", FmtValue::Number(0.0), true)
    );
    assert_eq!(
        cell(cells, 0, 4).d,
        render("mm-dd-yy", FmtValue::Number(1.0), true)
    );
    assert_eq!(
        cell(cells, 1, 2).d,
        render("General", FmtValue::Number(5.0), true)
    );
    assert_eq!(
        cell(cells, 1, 6).d,
        render("0.0000 \"widgets\"", FmtValue::Number(12.3456), true)
    );
}

#[test]
fn global_cell_cap_is_loud_and_preserves_extent() {
    let document = CalamineReader.read(
        &fixture("reader.xlsx"),
        ReaderOptions {
            max_cells: 4,
            ..ReaderOptions::default()
        },
    );

    assert!(document.ok);
    assert!(document.truncated);
    assert_eq!(document.sheets[0].cells.len(), 4);
    assert!(document.sheets[0].truncated);
    assert_eq!((document.sheets[0].rows, document.sheets[0].cols), (4, 7));
    assert_eq!(document.sheets[0].merges, ["A3:B3", "D3:F4"]);
}

#[test]
fn corrupt_zip_is_a_normalized_failure() {
    let document = CalamineReader.read(&fixture("corrupt.xlsx"), ReaderOptions::default());

    assert!(!document.ok);
    assert_eq!(
        document.error.expect("error should be populated").code,
        "bad_zip"
    );
}

#[test]
fn zero_timeout_is_reported_before_parsing() {
    let document = CalamineReader.read(
        &fixture("reader.xlsx"),
        ReaderOptions {
            timeout_ms: 0,
            ..ReaderOptions::default()
        },
    );

    assert!(!document.ok);
    assert_eq!(
        document.error.expect("error should be populated").code,
        "timeout"
    );
}

// These three binary smoke fixtures are copied unchanged from calamine
// v0.36.1 (git 0a24c2a9f1e38c0932c1299e633270dc730db505), MIT licensed:
// tests/date.xls, tests/issues.ods, and tests/date_1904.xlsb.
#[test]
fn legacy_xls_ods_and_xlsb_open_without_panicking() {
    for name in ["date.xls", "issues.ods", "date_1904.xlsb"] {
        let document = CalamineReader.read(&fixture(name), ReaderOptions::default());
        assert!(document.ok, "{name}: {:?}", document.error);
        assert!(!document.sheets.is_empty(), "{name}");
        assert!(
            document.sheets.iter().any(|sheet| !sheet.cells.is_empty()),
            "{name}"
        );
    }
}

#[test]
#[ignore = "requires the machine-local corpus payload via WAX_CORPUS_ROOT"]
fn corpus_spot_check_extracts_styles_and_widths_from_xlsx_and_xlsm() {
    let root = PathBuf::from(
        std::env::var("WAX_CORPUS_ROOT").expect("WAX_CORPUS_ROOT must point to corpus/files"),
    );
    let paths = [
        "poi/test-data/spreadsheet/63934.xlsx",
        "poi/test-data/spreadsheet/simple-monthly-budget.xlsx",
        "poi/test-data/spreadsheet/60512.xlsm",
    ];
    let mut styled_cells = 0;
    let mut widths = 0;
    for relative in paths {
        let document = CalamineReader.read(&root.join(relative), ReaderOptions::default());
        assert!(document.ok, "{relative}: {:?}", document.error);
        assert!(!document.styles.is_empty(), "{relative}: no styles");
        styled_cells += document
            .sheets
            .iter()
            .flat_map(|sheet| &sheet.cells)
            .filter(|cell| cell.s.is_some())
            .count();
        widths += document
            .sheets
            .iter()
            .map(|sheet| sheet.col_infos.len())
            .sum::<usize>();
    }
    assert!(styled_cells > 0);
    assert!(widths > 0);
}
