[package]
name = "wax-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "wax"
path = "src/main.rs"

[dependencies]
libc.workspace = true
serde_json.workspace = true
sha2.workspace = true
wax-core = { path = "../wax-core" }
wax-eval = { path = "../wax-eval" }
wax-proto = { path = "../wax-proto" }
wax-read = { path = "../wax-read" }
wax-store = { path = "../wax-store" }
wax-write = { path = "../wax-write" }

[dev-dependencies]
tempfile.workspace = true
