[package]
name = "wax-read"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
calamine.workspace = true
cfb = "0.14.0"
codepage = "0.1.2"
encoding_rs = "0.8.35"
quick-xml.workspace = true
wax-core = { path = "../wax-core" }
wax-fmt = { path = "../wax-fmt" }
wax-proto = { path = "../wax-proto" }
zip.workspace = true

[dev-dependencies]
serde_json.workspace = true
tempfile.workspace = true
