[package]
name = "wax-write"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
quick-xml.workspace = true
rust_xlsxwriter.workspace = true
tempfile.workspace = true
wax-core = { path = "../wax-core" }
wax-eval = { path = "../wax-eval" }
wax-fmt = { path = "../wax-fmt" }
wax-store = { path = "../wax-store" }
zip.workspace = true

[dev-dependencies]
wax-read = { path = "../wax-read" }
